#define CITRA_AUD_DLY_DELAY_BASE       CITRA_AUD_DLY_ADDRESS
#define CITRA_AUD_DLY_IN_BASE          (CITRA_AUD_DLY_DELAY_BASE + CITRA_AUD_DLY_IDLY_SEL0_OFFSET)
#define CITRA_AUD_DLY_IN_OFFSET        (CITRA_AUD_DLY_IDLY_SEL1_OFFSET - CITRA_AUD_DLY_IDLY_SEL0_OFFSET)
#define CITRA_AUD_DLY_INPUT_DELAY_ADDRESS(Input_Delay_INDEX) 		(CITRA_AUD_DLY_IN_BASE+((Input_Delay_INDEX)*(CITRA_AUD_DLY_IN_OFFSET)))
#define CITRA_AUD_DLY_OUT_BASE         (CITRA_AUD_DLY_DELAY_BASE + CITRA_AUD_DLY_ODLY_SEL0_OFFSET)
#define CITRA_AUD_DLY_OUT_OFFSET        (CITRA_AUD_DLY_ODLY_SEL1_OFFSET - CITRA_AUD_DLY_ODLY_SEL0_OFFSET)
#define CITRA_AUD_DLY_OUTPUT_DELAY_ADDRESS(Output_Delay_INDEX) 		(CITRA_AUD_DLY_OUT_BASE+((Output_Delay_INDEX)*(CITRA_AUD_DLY_OUT_OFFSET)))


